[package]
name = "cleopatra_cairo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["with_mimalloc"]
with_mimalloc = []

[dependencies]
mimalloc = { version = "0.1.29", default-features = false }
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
num-integer = "0.1.45"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11.1"
serde_json = "1.0"
hex = "0.4.3" 
bincode = "1.2.1"
starknet-crypto = "0.1.0"
clap = { version = "3.2.5", features = ["derive"] }
sha3 = "0.10.1"
lazy_static = "1.4.0"
nom = "7"
sha2 = {version="0.10.2", features=["compress"]}
generic-array = "0.14.6"
# This crate has only one function `take_until_unbalanced` that is
# very useful for our parsing purposes:
# https://stackoverflow.com/questions/70630556/parse-allowing-nested-parentheses-in-nom 
# There is a proposal for extending nom::delimited to use this function:
# https://github.com/Geal/nom/issues/1253
keccak = "0.1.2"
parse-hyperlinks = "0.23.4"

[dev-dependencies.rusty-hook]
version = "0.11"

[dev-dependencies.criterion]
version = "0.3"
features = ["html_reports"]

[[bench]]
path = "bench/criterion/criterion_benchmark.rs"
name = "criterion_benchmark"
harness = false

[[bin]]
name = "cleopatra-run"
path = "src/main.rs"
bench = false
doc = false
