[package]
name = "felt"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Field elements representation for the Cairo VM"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = "*"
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = "*"
lazy_static = "*"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
proptest = "1.0.0"
