[package]
name = "ensure-no_std"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
cairo-felt = { path = "../felt", default-features = false, features = [
    "alloc",
] }
cairo-vm = { path = "../vm", default-features = false }

wee_alloc = "0.4.5"


[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
