[package]
name = "hyper_threading"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true


[dependencies]
cairo-vm = { workspace = true, features = ["std"] }
rayon = "1.9.0"
tracing = "0.1.40"
