[package]
name = "cairo-vm-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-vm = { path = ".." }
clap = { version = "3.2.5", features = ["derive"] }
nom = "7"
thiserror = { version = "1.0.32" }
bincode = { tag = "v2.0.0-rc.2", git = "https://github.com/bincode-org/bincode.git" }
