[package]
name = "cairo1-run"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# To match the cairo-vm version used by cairo-lang-runner crate
cairo-vm = {version = "0.8.2", features = ["std"]}

cairo-lang-sierra-type-size = { version = "2.2.0", default-features = false } 
cairo-lang-sierra-to-casm.workspace = true 
cairo-lang-compiler.workspace = true
cairo-lang-sierra.workspace = true
cairo-lang-runner.workspace = true
cairo-lang-utils.workspace = true
itertools = "0.11.0"
clap = { version = "4.3.10", features = ["derive"] }
thiserror = { version = "1.0.40" }
bincode.workspace = true
assert_matches = "1.5.0"
rstest = "0.17.0"
