name: benchmark_pr 

on:
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust 1.62.1 
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.62.1 
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Python3 Build
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install test dependencies
      run: pip install ecdsa fastecdsa sympy cairo-lang==0.9.1
    - name: Run benchmark
      run: make benchmark-action
    - name: Cache benchmark report
      uses: actions//upload-artifact@master
      with:
        name: benchmark-report
        path: output.txt
    - name: Clean benches
      run: make clean
  upload-benchmark:
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - name: Retrieve cached report
      uses: actions/download-artifact@master
      with:
        name: benchmark-report
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'cargo'
        output-file: output.txt
        benchmark-data-dir-path: "."
        # Access token to deploy GitHub Pages branch
        github-token: ${{ secrets.GITHUB_TOKEN }}
        alert-threshold: '130%'
        comment-on-alert: true
        alert-comment-cc-users: '@unbalancedparentheses'
