name: 

on:
  workflow_call:
  push:
    branches: [ main ]

jobs:
  cache-cairo-programs:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Populate cache
      uses: actions/cache@v3
      id: cache-cairo-programs
      with:
        path: |
          cairo_programs/**.json
          cairo_programs/**.memory
          cairo_programs/**.trace
        key: cairo-cache-${{ hashFiles('**.cairo') }}
        restore-keys: cairo-cache-
    - name: Python3 Build
      if: ${{ steps.cache-cairo-programs.outputs.cache-hit != 'true' }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      if: ${{ steps.cache-cairo-programs.outputs.cache-hit != 'true' }}
      run: pip install ecdsa fastecdsa sympy cairo-lang==0.9.1
    - name: Compile Cairo programs
      if: ${{ steps.cache-cairo-programs.outputs.cache-hit != 'true' }}
      run: make -j cairo_test_programs cairo_proof_programs cairo_bench_programs cairo_trace
