name: "Fuzzer"

on:
  schedule:
  # At the end of every day
  - cron: "0 0 * * *"

jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

    - name: Run fuzzer
        # Run for three hours
        run: |
          cd fuzzer
          cargo hfuzz run fuzzer --run_time 10800
