name: Benchmark Hyper Threading

on:
  pull_request:
    branches: [ '**' ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        sudo apt update
        sudo apt-get install -y hyperfine

    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.74.1
      with:
        components: rustfmt, clippy

    - name: Compile PR Version
      run: |
        make cairo_bench_programs
        cargo build --release -p hyper_threading
        mkdir -p ${{ github.workspace }}/artifacts
        cp target/release/hyper_threading ${{ github.workspace }}/artifacts/hyper_threading_pr
        cp ./examples/hyper_threading/hyper-threading-workflow.sh ${{ github.workspace }}/artifacts/hyper-threading-workflow.sh
    
    - name: Upload PR Binary
      uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/artifacts/hyper_threading_pr

    - name: Upload Workflow Script
      uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/artifacts/hyper-threading-workflow.sh


    - name: Checkout Main Branch
      uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Compile Main Version
      run: |
        make cairo_bench_programs
        cargo build --release -p hyper_threading
        mkdir -p ${{ github.workspace }}/artifacts
        cp target/release/hyper_threading ${{ github.workspace }}/artifacts/hyper_threading_main

    - name: Upload Main Binary
      uses: actions/upload-artifact@v4
      with:
        path: ${{ github.workspace }}/artifacts/hyper_threading_main

    - name: Download Binaries and Script
      uses: actions/download-artifact@v4
      with:
        path: ${{ github.workspace }}/artifacts/


    - name: Display structure of downloaded files
      run: ls -R ${{ github.workspace }}/artifacts/

    - name: Run Benchmarks
      run: |
        ls -R ${{ github.workspace }}/artifacts/
        chmod +x ${{ github.workspace }}/artifacts/hyper-threading-workflow.sh
        ${{ github.workspace }}/artifacts/hyper-threading-workflow.sh

    - name: Compare Results
      run: |
        echo "PR Results:"
        cat results_pr.txt

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: results_pr.txt
