name: iai benchmarks

on:
  push:
    branches: [ main ]

jobs:
  cache-iai-results:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.61.0
          override: true
          profile: minimal
    - name: Python3 Build
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install test dependencies
      run: |
        pip install ecdsa fastecdsa sympy cairo-lang==0.9.1
        sudo apt update
        sudo apt install -y valgrind
    - uses: actions/checkout@v3
    # NB: this should never result in a hit, but rather just populate for PRs
    - name: Initialize IAI cache for ${{ github.event.push.head.sha }}
      uses: actions/cache@v3
      id: cache-iai-results
      with:
        path: |
          target/iai/
          !target/iai/**.old
        key: ${{ runner.os }}-iai-benchmark-cache-${{ github.event.push.head.sha }}
        restore-keys: |
          ${{ runner.os }}-iai-benchmark-cache-
    - name: Run iai benchmarks
      if: ${{ steps.cache-iai-results.outputs.cache-hit != 'true' }}
      run: make iai-benchmark-action
