name: rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust 1.61.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.61.0
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Python3 Build
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          /home/runner/.cargo/bin/
          /home/runner/.cargo/registry/index/
          /home/runner/.cargo/registry/cache/
          /home/runner/.cargo/git/db/
          /home/runner/work/cairo-rs/cairo-rs/target
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Install test dependencies
      run: pip install ecdsa fastecdsa sympy cairo-lang==0.9.1
    - name: format
      run: cargo fmt --all -- --check
    - name: Build
      run: make build
    - name: Run tests
      run: make -j test
    - name: Compare trace and memory
      run: make compare_trace_memory
    - name: Run clippy
      run: make clippy
    - name: Coverage
      run: make coverage
    - name: Cleanup tests
      run: make clean
    - name: Cache Codecov-report
      uses: actions//upload-artifact@master
      with:
        name: codecov-report
        path: target/tarpaulin
  upload-codecov:
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - name: Retrieve cached report
      uses: actions/download-artifact@master
      with:
        name: codecov-report
        path: target/tarpaulin
    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error:     true
    - name: Cleanup tests
      run: make clean
