name: rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up cargo cache
      id: fetch-cargo
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.rustup/
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock','**/Cargo.lock') }}

    - name: Install Rust 1.61.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.61.0
          default: true
          components: rustfmt, clippy

    - name: sanity
      run: ls -alh ~/
    - name: format
      run: cargo fmt --all -- --check
