name: rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust 1.61.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.61.0
          override: true
          components: rustfmt, clippy
    - uses: actions/checkout@v3
    - name: Python3 Build
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install test dependencies
      run: pip install ecdsa fastecdsa sympy cairo-lang==0.9.1
    - name: format
      run: cargo fmt --all -- --check
    - name: Build
      run: make build
    - name: Run tests
      run: make test
    - name: Compare trace and memory
      run: make compare_trace_memory
    - name: Run clippy
      run: make clippy
    - name: Coverage
      run: make coverage
    - name: Cleanup tests
      run: make clean
    - name: Cache Codecov-report
      uses: actions/cache@v2
      env:
        cache-name: cache-codecov
      with:
        path: target/tarpaulin
        keys: $codecov-report
  upload_codecov:
    runs-on: ubuntu-20.04
    steps:
    - name: Retrieve cached report
      uses: actions/cache@v2
      with:
        path: target/tarpaulin
        keys: $codecov-report
    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error:     true
