name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: install dependecies
      run: rustup component add rustfmt --toolchain 1.61.0-x86_64-unknown-linux-gnu
    - name: format
      run: cargo fmt --all -- --check
    - name: Build
      run: make build
    - name: Run tests
      run: make test
    - name: Run clippy
      run: make clippy
    - name: Coverage
      run: make coverage
