name: rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Install Rust 1.61.0
      uses: actions-rs/toolchain@v1
      with:
          toolchain: 1.61.0
          override: true
          components: rustfmt, clippy
    - name: Python3 Build
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install test dependencies
      run: pip install ecdsa fastecdsa sympy cairo-lang
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Format
      run: cargo fmt --all -- --check
    - name: Build
      run: make build
    - name: Populate cache
      uses: actions/cache@v3
      id: cache-cairo-programs
      with:
        path: |
          cairo_programs/**.json
          cairo_programs/**.memory
          cairo_programs/**.trace
          !cairo_programs/**.rs.*
        key: cairo-cache-${{ hashFiles( 'cairo_programs/**.cairo' ) }}
    - name: Restore timestamps
      uses: chetan/git-restore-mtime-action@v1
    - name: Install dependencies
      run: pip install ecdsa fastecdsa sympy cairo-lang==0.9.1
    - name: Run tests
      run: make -j test
    - name: Compare trace and memory
      run: make compare_trace_memory
    - name: Compare trace and memory with proof mode
      run: make compare_trace_memory_proof
    - name: Run clippy
      run: make clippy
    - name: Coverage
      run: make coverage
    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error:     true
