name: Test dependencies and cairo-vm install

on:
  merge_group:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  install:
    name: "Install on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: "Install dependencies"
        run: bash install.sh
      
      - name: "Compile project"
        run: cargo build --release

  install_debian:
    name: "Install on debian-11"
    runs-on: ubuntu-22.04
    container:
      image: debian:11
    defaults:
      run:
        shell: bash {0}

    steps:
      - uses: actions/checkout@v3

      - name: "Install dependencies"
        run: bash install.sh

      - name: "Compile project"
        run: |
          . "$HOME/.cargo/env"
          cargo build --release
