name: Test dependencies and cairo-rs install

on:
  push:
    branches-ignore: [ 'main' ]

jobs:
  os_install:
    name: "Install on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - if: matrix.os == 'ubuntu-22.04'
        run: install-scripts/ubuntu.sh

      - if: matrix.os == 'macos-12'
        run: install-scripts/macos.sh
