name: Test install

on:
  push:
    branches-ignore: [ 'main' ]

jobs:
  os_install:
    name: "Install deps and cairo-rs on ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - run: ls -lah / 
